http:
  hostname: "localhost"
  port: 8080
  readTimeout: "5s"
  writeTimeout: "10s"
  idleTimeout: "2m"
  tls:
    enabled: false
    certificate: ""
    key: ""
  session:
    key: <your JWT encryption key goes here>
    tokenAge: "24h"
    cookieAge: "24h"
    stores:
      cookieStore:
        enabled: "true"
      sqliteStore:
        enabled: "true"
        connection: "hyperserver.db?_journal=WAL&_timeout=5000&_fk=true"
        sessionTable: "session"
    types:
      default: sqliteStore
      visit: sqliteStore
      user: sqliteStore
      cookie: cookieStore
      sqlite: sqliteStore

auth:
  enabled: "true"
  jwtKey: <your auth token key goes here>
  verificationTokenExpiration: "24h"
  resetTokenExpiration: "1h"
  services:
    email:
      enabled: "false"

database:
  driver: "sqlite3"
  connection: "hyperserver.db?_journal=WAL&_timeout=5000&_fk=true"
  testConnection: ":memory:?_journal=WAL&_timeout=5000&_fk=true"

app:
  name: "HyperServer"
  workingDirectory: "D:/source/hyperserver"
  renderNotifications: "true"